version: '3'

services:

  market-mysql:
    image: mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root-pwd
      MYSQL_DATABASE: market
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      market-net:

  market-keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - '8888:8888'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ 'start-dev', '--http-port=8888' ]
    networks:
      market-net:

  market-app:
    build:
      context: ./images/app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - market-mysql
    volumes:
      - ../../backend:/app
    networks:
      market-net:

  market-frontend:
    build:
      context: ./images/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../../frontend/:/frontend
    networks:
      market-net:

  market-nginx:
    image: nginx:1.23-alpine
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../nginx/mime.types:/etc/nginx/mime.types
    ports:
      - '80:80'
    depends_on:
      - market-app
      - market-frontend
    networks:
      market-net:

networks:
  market-net:
